# Datawrapper configuration
#

domain: datawrapper.de
chart_domain: c.datawrapper.de

## show debug message?
debug: true

## some default values
default_theme: default
default_vis: bar-chart

## thumbnail sizes [width, height]
thumbnails:
    s: [150, 150]
    m: [260, 170]

## email address for admin
admin_email: hello@datawrapper.de
log_email: debug@datawrapper.de

## prevent guest from creating charts
prevent_guest_charts: false

## prevent guests from creating accounts
## (an admin need to create the account)
prevent_guest_access: false

## the following links are shown in the footer
## please link to your own imprint (and not ours)
footer_links:
    - title:
        en: Quick Start
        de: Schnellstart
      url: http://docs.datawrapper.de/%lang/quickstart
    - title:
        en: Tutorial
        de: Tutorial
      url: http://docs.datawrapper.de/%lang/tutorial

## to use a custom home page in your installation
## uncomment the following setting and create a new
## Twig template (e.g. my-home.twig) in /templates/custom/
# custom_home: my-home


## HTTP AUTH (optional)
## edit and uncomment if Datawrapper is locked behind HTTP Auth
# http_auth: username:password


## TOP NAV MENU (optional)
## edit and uncomment to add further links to the nav menu
# navigation:
#   - id: about
#     title: About
#     url: http://docs.datawrapper.de/%lang%/
#     icon: info-sign
#   - id: blog
#     title: Blog
#     url: http://blog.datawrapper.de
#     icon: tag


## ANALYTICS (optional)
## configure analytics module, e.g. Piwik
# analytics:
#     type: Piwik
#     config:
#         url: piwik.datawrapper.de  # without http:// and trailing slash
#         idSite: 5


## PUBLISH (optional)
## configure CDN publication module, e.g. Amazon S3
# publish:
#     type: S3
#     requires:
#       - vendor/s3/S3.php
#     config:
#         accesskey: YOUR_ACCESS_KEY
#         secretkey: YOUR_SECRET_KEY
#         bucket: your-bucket


## PHANTOMJS (optional)
## edit and uncomment to enable static image chart exporting
# phantomjs:
#     path: /path/to/phantomjs


########################################################
#                                                      #
#  Anything below this line is for debugging/testing   #
#  only and thus can safely be ignored.                #
#                                                      #
########################################################

## if set to true, datawrapper will display a button for
## simplifying creation of test cases
# debug_export_test_cases: true

## create_test_charts.php creates a test user who owns
## the test charts, and will get the following password:
# testuser_pwd: '1234'
